### ISSUE TITLE
Support for Multi-server Players

### ISSUE THREAD

**Issue by pagem** [ko-vasilev/Hearthstone-Collection-Tracker#1]
Hi, 

I love the idea of this plugin which would help me ditch the spreadsheet I currently use to track my collections. Shame you cannot "load" the cards somehow from the game itself but I guess that might be difficult. This is not so much an issue as a feature request:

--> I was wondering if there is anyway you can add support for multiple servers? I play on NA, EU and PA and as Blizz wants to keep my gaming profile separate in each region I have ended up with three card collections.

--> Also it would be great if when I use the NetDeck Chrome plugin to import a deck from say Hearthpwn I get a message telling me if I have any cards missing in my collection needed before I can build and run the deck.

Anyway look forward to picking up any updates and feel free to contact me if you need any beta testing.

Pagem.

**Comment by NLZ** [comment]
Detecting should be possible with the HSDT's Export to Hearthstone function. You just have to manually run it for every heroes.

**Comment by GiggliG** [comment]
I second the OP's request: I play on NA and EU, and this plugin is no use to me unless I can keep separate collections for each.

**Comment by ko-vasilev** [comment]
Guys, support of multiple collections will be definitely added in the next release!
About NetDeck importing: I think this is currently not possible since developer of HDT did not provide any way of handling import. I'll check if I can manually set for example tag "Missing cards" to the decks if you don't have the cards required.
@NLZ I think it is much easier to fill in the collection by yourself since the import function not always works correctly so anyways you will have to check the correctness by yourself. For my collection it took me about 15 minutes to fill, not so much as I concern.

**Comment by NLZ** [comment]
Import function is fixed in the latest update so it works fine now. But I understand, it could be hard to make it.
I was just saying because right now there is not really any function that would make me dich [this spreadsheet](https://docs.google.com/spreadsheets/d/1VdqhpiremPEiIKmS1YI8_8HkdYb57wb8cD4ZLnxtffU/edit#gid=357052481).

**Comment by ko-vasilev** [comment]
What functions would you like to see in this plugin? I'm opened to any suggestions to improve it!
I think your spreadsheet is just overwhelmed with the information.
Initially I wanted to replace my spreadsheet which is basically tracks on what cards am I missing and what packs it would be better to buy.

**Comment by GiggliG** [comment]
I'm glad to here multi-server collections will be supported. Awesome.

**Comment by ko-vasilev** [comment]
Fixed with commit 59884d0cae1affc4357e322dbbd50c7408889d13
