### ISSUE TITLE
Importing in V 3.0 doesnt work

### ISSUE THREAD

**Issue by manousos13** [ko-vasilev/Hearthstone-Collection-Tracker#74]
it seems that it just makes , its first search and then stucks there forever

**Comment by koppite** [comment]
@ko-vasilev this is because the ScreenCapture.CaptureHearthstone gets stuck on the await delegate forever inside HDT.  This may be a bug for @Epix37 to look at in HDT because I think this is the only place that calls that async version of it.   

A workaround is to use _ScreenCapture.CaptureScreen(handle, point, width, height)_ as it isn't async and that will work for the time being.

**Comment by azeier** [comment]
Fixed with https://github.com/Epix37/Hearthstone-Deck-Tracker/commit/129ca56cef5c5e00f7e8c882c389b8718e1879d9.
